[package]
name = "mrdirector"
version = "0.1.0"
edition = "2021"
description = "A narrative game development package for the Turbo Game Engine."
license = "GNU GPLv3"

[dependencies]
turbo = { package = "turbo-genesis-sdk", version = "1.6.2" }